openapi: 3.0.1
info:
  title: TP TACS
  version: 1.0.0
tags:
  - name: Auth
    description: Autenticación
  - name: Provincias
    description: Operaciones sobre provincias
  - name: Usuarios
    description: Operaciones sobre usuarios
  - name: Partidas
    description: Operaciones sobre partidas
  - name: Admin
    description: Operaciones administrativas
paths:
  /auth/logIn:
    post:
      tags:
        - Auth
      summary: login
      operationId: logIn
      description: Loguea a un usuario validando su Google Id Token y retornando un JWT de la aplicación
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleAuthModel'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NuevoJWTModel'
        400:
          description: Bad request
        401:
          description: Fail
  /auth/signUp:
    post:
      tags:
        - Auth
      summary: singUp
      operationId: singUp
      description: Registro a un usuario nuevo y retorna un JWT de la aplicación
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleAuthModel'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NuevoJWTModel'
        400:
          description: Bad request
        401:
          description: Fail
  /admin/estadisticas:
    get:
      tags:
        - Admin
      summary: Obtiene las estadísticas generales del juego
      operationId: getEstadisticas
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: fechaInicio
          schema:
            type: string
            format: date
          required: false
        - in: query
          name: fechaFin
          schema:
            type: string
            format: date
          required: false
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstadisticasDeJuegoModel'
        400:
          description: Bad request
        403:
          description: Forbbiden
  /admin/scoreboard:
    get:
      tags:
        - Admin
      summary: Retorna los datos del scoreboard
      operationId: getScoreboard
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          required: false
        - in: query
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EstadisticasDeUsuarioModel'
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Page not found
  /admin/estadisticas/usuarios/{idUsuario}:
    get:
      tags:
        - Admin
      summary: Obtiene las estadísticas particulares de un usuario
      operationId: getEstadisticasDeUsuario
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: idUsuario
          description: Id del usuario
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstadisticasDeUsuarioModel'
        400:
          description: Bad request
        # En el caso de que no se tengan permisos, también se retorna 404
        404:
          description: Page not found
  /usuarios:
    get:
      tags:
        - Usuarios
      summary: Permite listar a los usuarios
      operationId: listarUsuarios
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: filter
          schema:
            type: string
          required: false
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          required: false
        - in: query
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsuarioModel'
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Page not found
  /provincias:
    get:
      tags:
        - Provincias
      summary: Permite listar las provincias
      operationId: listarProvincias
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          required: false
        - in: query
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProvinciaModel'
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Page not found
  /partidas:
    get:
      tags:
        - Partidas
      summary: Permite listar partidas. No incluye los datos de juego asociados a las mismas.
      operationId: listarPartidas
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: fechaInicio
          schema:
            type: string
            format: date
          required: false
        - in: query
          name: fechaFin
          schema:
            type: string
            format: date
          required: false
        - in: query
          name: estado
          schema:
            $ref: '#/components/schemas/EstadoDeJuegoModel'
          required: false
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          required: false
        - in: query
          name: page
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartidaModel'
        400:
          description: Bad request
        403:
          description: Forbidden
    post:
      tags:
        - Partidas
      summary: Crear una nueva pertida
      operationId: crearPartida
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: crearPartidaBody
              properties:
                idProvincia:
                  type: integer
                  description: Id de la provincia donde se juega
                cantidadMunicipios:
                  type: integer
                  description: Cantidad de municipios que se usan
                idJugadores:
                  description: Jugadores
                  type: array
                  items:
                    type: integer
                modoDeJuego:
                  $ref: '#/components/schemas/ModoDeJuegoModel'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        403:
          description: Forbidden
        404:
          description: Not found
  /partidas/{idPartida}:
    get:
      tags:
        - Partidas
      summary: "Retorna la partida con id: idPartida. Incluye los datos del juego."
      operationId: getPartida
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: idPartida
          description: Id de la partida
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartidaModel'
        400:
          description: Bad Request
        404:
          description: Not found
    patch:
      tags:
        - Partidas
      summary: Actualiza el estado de una partida
      operationId: actualizarEstadoPartida
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: idPartida
          schema:
            type: integer
          required: true
        - in: query
          name: estado
          schema:
            $ref: '#/components/schemas/EstadoDeJuegoModel'
          required: true
      responses:
        200:
          description: Success
        400:
          description: Bad request
        404:
          description: Not found
  /partidas/{idPartida}/movimientos:
    post:
      tags:
        - Partidas
      summary: Mueve gauchos de un municipio a otro
      operationId: moverGauchos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: idPartida
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: moverGauchosBody
              properties:
                idMunicipioOrigen:
                  type: integer
                  description: Id del municipio de origen
                idMunicipioDestino:
                  type: integer
                  description: Id del municipio de destino
                cantidad:
                  type: integer
                  description: Cantidad de gauchos a mover
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                title: moverGauchosResponse
                properties:
                  municipioOrigen:
                    $ref: '#/components/schemas/MunicipioEnJuegoModel'
                  municipioDestino:
                    $ref: '#/components/schemas/MunicipioEnJuegoModel'
        400:
          description: Bad request
        404:
          description: Not found
  /partidas/{idPartida}/ataques:
    post:
      tags:
        - Partidas
      summary: Ataca a un municipio
      operationId: atacarMunicipio
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: idPartida
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: atacarMunicipioBody
              properties:
                idMunicipioAtacante:
                  type: integer
                  description: Id del municipio que ataca
                idMunicipioObjetivo:
                  type: integer
                  description: Id del municipio atacado
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                title: atacarMunicipioResponse
                properties:
                  municipioAtacante:
                    $ref: '#/components/schemas/MunicipioEnJuegoModel'
                  municipioAtacado:
                    $ref: '#/components/schemas/MunicipioEnJuegoModel'
        400:
          description: Bad request
        404:
          description: Not found
components:
  schemas:
    PartidaModel:
      type: object
      description: Una partida
      required:
        - id
        - provincia
        - cantidadMunicipios
        - estado
        - jugadores
        - modoDeJuego
        - fecha
      properties:
        id:
          type: integer
          description: Id de la partida
        provincia:
          $ref: '#/components/schemas/ProvinciaModel'
        cantidadMunicipios:
          type: number
          description: Cantidad de municipios que se usan
        estado:
          $ref: '#/components/schemas/EstadoDeJuegoModel'
        jugadores:
          type: array
          description: Usuarios que juegan esta partida
          items:
            $ref: '#/components/schemas/UsuarioModel'
        modoDeJuego:
          $ref: '#/components/schemas/ModoDeJuegoModel'
        fecha:
          type: string
          format: date
          description: Fecha de inicio de la partida
        informacionDeJuego:
          $ref: '#/components/schemas/DatosDeJuegoModel'
        idGanador:
          type: string
          description: Id del usuario ganador
    DatosDeJuegoModel:
      type: object
      description: Datos de una partida. Incluye su provincia en juego y el usuario que tiene el proximo turno.
      required:
        - provincia
      properties:
        proximoTurno:
          $ref: '#/components/schemas/UsuarioModel'
        provincia:
          $ref: '#/components/schemas/ProvinciaEnJuegoModel'
    EstadoDeJuegoModel:
      type: string
      description: Estado de una partida.
      enum:
        - EnProgreso
        - Terminada
        - Cancelada
    ModoDeJuegoModel:
      type: string
      description: Modo de juego.
      enum:
        - Rapido
        - Normal
        - Extendido
    UsuarioModel:
      type: object
      description: Un usuario.
      required:
        - id
        - nombreDeUsuario
      properties:
        id:
          type: integer
        nombreDeUsuario:
          type: string
    ProvinciaModel:
      type: object
      description: Una provincia.
      required:
        - id
        - nombre
      properties:
        id:
          type: integer
          description: Id de la provincia
        nombre:
          type: string
          description: Nombre de la provincia
    ProvinciaEnJuegoModel:
      type: object
      description: Provincia en juego.
      required:
        - municipios
      properties:
        municipios:
          type: array
          description: Municipios en juego que contiene la provincia.
          items:
            $ref: '#/components/schemas/MunicipioEnJuegoModel'
    MunicipioEnJuegoModel:
      type: object
      description: Municipio en juego.
      required:
        - id
        - nombre
        - ubicacion
        - duenio
        - gauchos
      properties:
        id:
          type: integer
          description: Id del municipio.
        nombre:
          type: string
          description: Nombre del municipio.
        ubicacion:
          $ref: '#/components/schemas/CoordenadasModel'
        duenio:
          $ref: '#/components/schemas/UsuarioModel'
        gauchos:
          type: integer
          description: Cantidad de gauchos en el municipio.
        modo:
          $ref: '#/components/schemas/ModoDeMunicipioModel'
        estaBloqueado:
          type: boolean
          description: Si el municipio está bloqueado.
    CoordenadasModel:
      type: object
      required:
        - lat
        - lon
      description: Par de coordenadas en el mundo.
      properties:
        lat:
          type: number
          description: Latitud
        lon:
          type: number
          description: Longitud
    ModoDeMunicipioModel:
      type: string
      description: Modo de operación de un municipio.
      enum:
        - Defensa
        - Produccion
    GoogleAuthModel:
      type: object
      required:
        - idToken
      properties:
        idToken:
          description: Google Id Token del usuario
          type: string
    NuevoJWTModel:
      type: object
      required:
        - token
      properties:
        usuario:
          $ref: '#/components/schemas/UsuarioModel'
        token:
          description: JWT que puede utilizarse para acceder a los recursos protegidos
          type: string
    EstadisticasDeJuegoModel:
      type: object
      properties:
        partidasCreadas:
          type: integer
        partidasEnCurso:
          type: integer
        partidesTerminadas:
          type: integer
        partidasCanceladas:
          type: integer
    EstadisticasDeUsuarioModel:
      type: object
      properties:
        usuario:
          $ref: '#/components/schemas/UsuarioModel'
        partidasJugadas:
          type: integer
        partidasGanadas:
          type: integer
        rachaActual:
          type: integer
          description: Racha actual de victorias
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT