version: "3.8"

services:
  api:
    build: "./"
    container_name: "tacs-api"
    environment:
     - JWT_SECRET
     - GOOGLE_OAUTH_CLIENT_ID="475854452552-js6cnac0fjktpav4dcp570860l7etar8.apps.googleusercontent.com"
    networks:
     - "tacs-net"
  frontend:
    build: "./tacs-frontend"
    container_name: "tacs-frontend"
    networks:
     - "tacs-net"
  web:
    image: nginx
    container_name: "tacs-reverse-proxy"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:8080"
    networks:
     - "tacs-net"

networks:
  tacs-net:
    driver: bridge
