version: "3.8"

services:
  db:
    image: mongo:4.4
    container_name: "tacs-db"
    volumes:
      - tacs_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - "tacs-net"
  api:
    build: "./"
    container_name: "tacs-api"
    environment:
     - JWT_SECRET
     - GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
     - DB_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
    networks:
     - "tacs-net"
  frontend:
    build: "./tacs-frontend"
    container_name: "tacs-frontend"
    networks:
     - "tacs-net"
  web:
    image: nginx
    container_name: "tacs-reverse-proxy"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:8080"
    networks:
     - "tacs-net"

networks:
  tacs-net:
    driver: bridge

volumes:
  tacs_data:
    driver: local
