/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.17-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package tp.tacs.api.controllers;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.threeten.bp.LocalDate;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import tp.tacs.api.models.AtacarMunicipioBody;
import tp.tacs.api.models.CrearPartidaBody;
import tp.tacs.api.models.EjecutarAccionEntreMunicipiosBody;
import tp.tacs.api.models.EjecutarAccionEntreMunicipiosResponse;
import tp.tacs.api.models.EstadoDeJuego;
import tp.tacs.api.models.MoverGauchosBody;
import tp.tacs.api.models.Partida;
import tp.tacs.api.models.ResultadoAtaque;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-08-27T18:00:30.287-03:00[America/Buenos_Aires]")
@Api(value = "partidas", description = "the partidas API")
public interface PartidasApi {

    @ApiOperation(value = "Actualiza el estado de una partida", nickname = "actualizarEstadoPartida", notes = "", tags={ "Games", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 400, message = "Bad request"),
        @ApiResponse(code = 404, message = "Not found"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/partidas/{idPartida}",
        method = RequestMethod.PATCH)
    ResponseEntity<Void> actualizarEstadoPartida(@ApiParam(value = "",required=true) @PathVariable("idPartida") Integer idPartida
,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "estado", required = true) EstadoDeJuego estado
);


    @ApiOperation(value = "(Opción 1 para ataques) Ataca a un municipio", nickname = "atacarMunicipio", notes = "", response = ResultadoAtaque.class, tags={ "Partidas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = ResultadoAtaque.class),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not found"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/partidas/{idPartida}/municipios/ataques",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ResultadoAtaque> atacarMunicipio(@ApiParam(value = "",required=true) @PathVariable("idPartida") Integer idPartida
,@ApiParam(value = ""  )  @Valid @RequestBody AtacarMunicipioBody body
);


    @ApiOperation(value = "Crear una nueva pertida", nickname = "crearPartida", notes = "", tags={ "Partidas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 400, message = "Bad Request") })
    @RequestMapping(value = "/partidas",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> crearPartida(@ApiParam(value = ""  )  @Valid @RequestBody CrearPartidaBody body
);


    @ApiOperation(value = "(Opción 2 para movimientos y ataques) Crea una acción entre dos municipios", nickname = "ejecutarAccionEntreMunicipios", notes = "", response = EjecutarAccionEntreMunicipiosResponse.class, tags={ "Partidas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = EjecutarAccionEntreMunicipiosResponse.class),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "NotFound"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/partidas/{idPartida}/acciones",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<EjecutarAccionEntreMunicipiosResponse> ejecutarAccionEntreMunicipios(@ApiParam(value = "",required=true) @PathVariable("idPartida") Integer idPartida
,@ApiParam(value = ""  )  @Valid @RequestBody EjecutarAccionEntreMunicipiosBody body
);


    @ApiOperation(value = "Retorna la partida con id: idPartida. Incluye los datos del juego.", nickname = "getPartida", notes = "", response = Partida.class, tags={ "Partidas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Partida.class),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not found") })
    @RequestMapping(value = "/partidas/{idPartida}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Partida> getPartida(@ApiParam(value = "Id de la partida",required=true) @PathVariable("idPartida") Integer idPartida
);


    @ApiOperation(value = "Permite listar partidas. No incluye los datos de juego asociados a las mismas.", nickname = "listarPartidas", notes = "", response = Partida.class, responseContainer = "List", tags={ "Partidas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Partida.class, responseContainer = "List"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/partidas",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Partida>> listarPartidas(@ApiParam(value = "") @Valid @RequestParam(value = "fechaInicio", required = false) LocalDate fechaInicio
,@ApiParam(value = "") @Valid @RequestParam(value = "fechaFin", required = false) LocalDate fechaFin
,@ApiParam(value = "") @Valid @RequestParam(value = "estado", required = false) EstadoDeJuego estado
);


    @ApiOperation(value = "(Opción 1 para movimientos) Mueve gauchos de un municipio a otro", nickname = "moverGauchos", notes = "", tags={ "Partidas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not found"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/partidas/{idPartida}/municipios/movimientos",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> moverGauchos(@ApiParam(value = "",required=true) @PathVariable("idPartida") Integer idPartida
,@ApiParam(value = ""  )  @Valid @RequestBody MoverGauchosBody body
);

}
