/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.17-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package tp.tacs.api.controllers;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import tp.tacs.api.models.Provincia;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-08-27T18:00:30.287-03:00[America/Buenos_Aires]")
@Api(value = "provincias", description = "the provincias API")
public interface ProvinciasApi {

    @ApiOperation(value = "Permite listar las provincias", nickname = "listarProvincias", notes = "", response = Provincia.class, responseContainer = "List", tags={ "Provincias", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Provincia.class, responseContainer = "List"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/provincias",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Provincia>> listarProvincias();

}
