/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.17-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package tp.tacs.api.controllers;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import tp.tacs.api.models.Usuario;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-08-27T18:00:30.287-03:00[America/Buenos_Aires]")
@Api(value = "usuarios", description = "the usuarios API")
public interface UsuariosApi {

    @ApiOperation(value = "Permite listar a los usuarios", nickname = "listarUsuarios", notes = "", response = Usuario.class, responseContainer = "List", tags={ "Usuarios", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Usuario.class, responseContainer = "List") })
    @RequestMapping(value = "/usuarios",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Usuario>> listarUsuarios(@ApiParam(value = "") @Valid @RequestParam(value = "filter", required = false) String filter
);

}
