security:
  jwt:
    secret: ${JWT_SECRET:secret}
    issuer: Grupo3
  google:
    clientId: ${GOOGLE_OAUTH_CLIENT_ID:secret}
  rutas:
    permitidas: /auth/logIn,/auth/signUp
    administrativas: "/admin/**"
